config/routes.rb
Rails.application.routes.draw do
  resources :hotlines
  resources :locations

  root 'welcome#index'

end

app/models/area.rb
class Area < ActiveRecord::Base
end

app/models/hotline.rb
class Hotline < ActiveRecord::Base
end

app/models/location.rb
class Location < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/hotlines_controller.rb
class HotlinesController < ApplicationController
  before_action :set_hotline, only: [:show, :edit, :update, :destroy]

  # GET /hotlines
  # GET /hotlines.json
  def index
    @hotlines = Hotline.all
  end

  # GET /hotlines/1
  # GET /hotlines/1.json
  def show
  end

  # GET /hotlines/new
  def new
    @hotline = Hotline.new
  end

  # GET /hotlines/1/edit
  def edit
  end

  # POST /hotlines
  # POST /hotlines.json
  def create
    @hotline = Hotline.new(hotline_params)

    respond_to do |format|
      if @hotline.save
        format.html { redirect_to @hotline, notice: 'Hotline was successfully created.' }
        format.json { render :show, status: :created, location: @hotline }
      else
        format.html { render :new }
        format.json { render json: @hotline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hotlines/1
  # PATCH/PUT /hotlines/1.json
  def update
    respond_to do |format|
      if @hotline.update(hotline_params)
        format.html { redirect_to @hotline, notice: 'Hotline was successfully updated.' }
        format.json { render :show, status: :ok, location: @hotline }
      else
        format.html { render :edit }
        format.json { render json: @hotline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotlines/1
  # DELETE /hotlines/1.json
  def destroy
    @hotline.destroy
    respond_to do |format|
      format.html { redirect_to hotlines_url, notice: 'Hotline was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hotline
      @hotline = Hotline.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hotline_params
      params.require(:hotline).permit(:name, :number, :link, :donate, :category, :hours, :description)
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:name, :tags, :entry)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hotlines_helper.rb
module HotlinesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/hotlines/_form.html.erb
<%= form_for(@hotline) do |f| %>
  <% if @hotline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hotline.errors.count, "error") %> prohibited this hotline from being saved:</h2>

      <ul>
      <% @hotline.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :number %><br>
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :donate %><br>
    <%= f.text_field :donate %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :hours %><br>
    <%= f.text_field :hours %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hotlines/edit.html.erb
<h1>Editing Hotline</h1>

<%= render 'form' %>

<%= link_to 'Show', @hotline %> |
<%= link_to 'Back', hotlines_path %>

app/views/hotlines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Hotlines</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Number</th>
      <th>Link</th>
      <th>Donate</th>
      <th>Category</th>
      <th>Hours</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hotlines.each do |hotline| %>
      <tr>
        <td><%= hotline.name %></td>
        <td><%= hotline.number %></td>
        <td><%= hotline.link %></td>
        <td><%= hotline.donate %></td>
        <td><%= hotline.category %></td>
        <td><%= hotline.hours %></td>
        <td><%= hotline.description %></td>
        <td><%= link_to 'Show', hotline %></td>
        <td><%= link_to 'Edit', edit_hotline_path(hotline) %></td>
        <td><%= link_to 'Destroy', hotline, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hotline', new_hotline_path %>

app/views/hotlines/new.html.erb
<h1>New Hotline</h1>

<%= render 'form' %>

<%= link_to 'Back', hotlines_path %>

app/views/hotlines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @hotline.name %>
</p>

<p>
  <strong>Number:</strong>
  <%= @hotline.number %>
</p>

<p>
  <strong>Link:</strong>
  <%= @hotline.link %>
</p>

<p>
  <strong>Donate:</strong>
  <%= @hotline.donate %>
</p>

<p>
  <strong>Category:</strong>
  <%= @hotline.category %>
</p>

<p>
  <strong>Hours:</strong>
  <%= @hotline.hours %>
</p>

<p>
  <strong>Description:</strong>
  <%= @hotline.description %>
</p>

<%= link_to 'Edit', edit_hotline_path(@hotline) %> |
<%= link_to 'Back', hotlines_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myhotline</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-light navbar-fixed-top">
  <a class="navbar-brand" href="#">Project name</a>
  <ul class="nav navbar-nav">
    <li class="nav-item active">
      <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">About</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Contact</a>
    </li>
  </ul>
</nav>

<div class="container">
    <%= yield %>
</div>

</body>
</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :tags %><br>
    <%= f.text_field :tags %>
  </div>
  <div class="field">
    <%= f.label :entry %><br>
    <%= f.text_field :entry %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Locations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Tags</th>
      <th>Entry</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.name %></td>
        <td><%= location.tags %></td>
        <td><%= location.entry %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @location.name %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @location.tags %>
</p>

<p>
  <strong>Entry:</strong>
  <%= @location.entry %>
</p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>

app/views/welcome/index.html.erb
<section class="row center full-height">
  <div class="col-md-8 col-md-offset-2 vertically-align">
    <div class="">
      <h1>Find a hotline near</h1>  <input class="form-control form-control-lg form-transparent" type="text" placeholder="City">
    </div>
  </div>
</section>